project1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("testapp.urls"))
]

testapp/urls.py
from django.urls import path
from . import views

app_name = "testapp"

urlpatterns = [
    path('',views.home,name="home"),
    path('about', views.about, name="about"),
    path('login', views.login, name="login"),
    path('register', views.register, name="register")
]

testapp/models.py
from django.db import models

# Create your models here.

testapp/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views he
def home(request):
    return render(request,'index.html')


def about(request):
    return render(request, 'about.html')

def login(request):
    return render(request, 'login.html')

def register(request):
    return render(request, 'register.html')

testapp/templates/about.html
{% extends 'base.html' %}

{% block about %}

<p>About page</p>

{% endblock %}

testapp/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>
<a href="{% url 'testapp:home' %}">Home</a>
<a href="{% url 'testapp:about' %}">About</a>
<a href="{% url 'testapp:login' %}">Login</a>
<a href="{% url 'testapp:register' %}">Register</a>


{% block body %}


{% endblock %}

{% block about %}

{% endblock %}

{% block login %}

{% endblock %}

{% block register %}


{% endblock %}

</body>
</html>

testapp/templates/index.html
{% extends 'base.html' %}

{% block body %}
     <p>Homepage</p>
{% endblock %}

testapp/templates/login.html
{% extends 'base.html' %}

{% block login %}
    <h1 class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4",">Sign In</h1>
     <form style="margin-left: 250px">
  <!-- Email input -->
  <div style="padding-left: 150px">

      <div class="form-outline mb-4" style="width: 250px">
    <input type="email" id="form2Example1" class="form-control" />
    <label class="form-label" for="form2Example1">Email address</label>
  </div>

  <!-- Password input -->
  <div class="form-outline mb-4" style="width: 250px">
    <input type="password" id="form2Example2" class="form-control" />
    <label class="form-label" for="form2Example2">Password</label>
  </div>
  <button type="button" class="btn btn-primary btn-block mb-4">Sign in</button>

  </div>

  <!-- 2 column grid layout for inline styling -->


  <!-- Submit button -->


  <!-- Register buttons -->
  <div style="padding-left: 400px">
    <p style="margin-left: -250px">Not a member? <a href="{% url 'testapp:register' %}">Register</a></p>

    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-facebook-f"></i>
    </button>

    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-google"></i>
    </button>

    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-twitter"></i>
    </button>

    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-github"></i>
    </button>
  </div>
</form>
{% endblock %}

testapp/templates/register.html
{% extends 'base.html' %}

{% block register %}
    <section class="vh-100" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>

                <form class="mx-1 mx-md-4">

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="text" id="form3Example1c" class="form-control" />
                      <label class="form-label" for="form3Example1c">Your Name</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="email" id="form3Example3c" class="form-control" />
                      <label class="form-label" for="form3Example3c">Your Email</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="password" id="form3Example4c" class="form-control" />
                      <label class="form-label" for="form3Example4c">Password</label>
                    </div>
                  </div>





                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <a href="{% url 'testapp:login' %}">
                          <button type="button" class="btn btn-primary btn-lg">Register</button>
                      </a>
                  </div>

                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}